[package]
name = "fractal"
version = "0.0.1"
authors = ["William (B.J.) Snow Orvis <aetherknight@gmail.com>"]
description = "Fractal rendering program"


[[bin]]
name = "fractal"
doc = false

[dependencies]
docopt = "~0.6.0"
piston = "0.17.0"
piston2d-graphics = "0.13.1"
piston_window = "0.34.0"
rand = "0.3"
rustc-serialize = "^0.3"

#[dev-dependencies]
#float-cmp = "~0.2.1"
