[package]
name = "fractal"
version = "0.1.0"
authors = ["William (B.J.) Snow Orvis <aetherknight@gmail.com>"]
description = "Fractal rendering program"

[dependencies]
piston = "0.16.0"
piston2d-graphics = "0.11.0"
pistoncore-glutin_window = "0.19.0"
piston2d-opengl_graphics = "0.20.0"

#[dev-dependencies]
#float-cmp = "~0.2.1"
