[package]
name = "fractal-piston"
version = "0.0.1"
authors = ["William (B.J.) Snow Orvis <aetherknight@gmail.com>"]
license = "Apache-2.0"
description = "Fractal rendering program"
edition = "2018"

[[bin]]
name = "fractal-piston"
doc = false

[dependencies]
fractal-lib = { path = "../fractal-lib" }
clap = "2"
gfx_device_gl = "^0.16.2"  # needs to match piston_window/dependencies
image = "~0.23.0"  # needs to match piston_window/dependencies
num = "^0.2"
num_cpus = "^1.9"
piston = "^0.49.0"
piston2d-graphics = "^0.36.0"
piston_window = "0.107.0"
time = "~0.1"
