[package]
name = "fractal-wasm"
version = "0.0.1"
authors = ["William (B.J.) Snow Orvis <aetherknight@gmail.com>"]
license = "Apache-2.0"
description = "Fractal rendering program, targeting webassembly"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.6"
fractal-lib = { path = "../fractal-lib", features = ["wasm-bindgen"]}
js-sys = "0.3.9"
num = "^0.2"
paste = "0.1.5"
wasm-bindgen = "0.2.42"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'console',
  'CanvasRenderingContext2d',
  'HtmlCanvasElement',
  'ImageData',
]

# [profile.release]
# lto = true
# opt-level = 's'
