[package]
name = "fractal-wasm"
version = "0.0.1"
authors = ["William (B.J.) Snow Orvis <aetherknight@gmail.com>"]
description = "Fractal rendering program, targeting webassembly"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
fractal-lib = { path = "../fractal-lib" }
wasm-bindgen = "0.2.42"
vecmath = "0.3.1"
js-sys = "0.3.9"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'console',
  'CanvasRenderingContext2d',
  'HtmlCanvasElement',
]
